use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq)]
pub struct OutputMode {
    pub width: i32,
    pub height: i32,
    pub refresh_rate: f32,
    pub current: bool,
    pub preferred: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Output {
    pub name: String,
    pub description: String,
    pub make: String,
    pub model: String,
    pub serial: String,
    pub physical_size: String,
    pub position: (i32, i32),
    pub scale: f32,
    pub transform: String,
    pub modes: Vec<OutputMode>,
    pub enabled: bool,
}

pub fn save_config(
    outputs: &[Output],
    settings: &crate::settings::AppSettings,
) -> Result<(), String> {
    let mut script = String::from("# Generated by mango-display\n\n");

    for out in outputs {
        if out.enabled {
            let rr = match out.transform.as_str() {
                "normal" => 0,
                "90" => 1,
                "180" => 2,
                "270" => 3,
                "flipped" => 4,
                "flipped-90" => 5,
                "flipped-180" => 6,
                "flipped-270" => 7,
                _ => 0,
            };

            let mut w = 0;
            let mut h = 0;
            let mut r = 0.0;

            if let Some(current_mode) = out.modes.iter().find(|m| m.current) {
                w = current_mode.width;
                h = current_mode.height;
                r = current_mode.refresh_rate;
            }

            script.push_str(&format!(
                "monitorrule=name:{},width:{},height:{},refresh:{:.6},x:{},y:{},scale:{:.6},rr:{}\n",
                out.name, w, h, r, out.position.0, out.position.1, out.scale, rr
            ));
        }
    }

    let expand_path = |p: &str| -> Result<PathBuf, String> {
        if p.starts_with("~/") {
            let home = dirs::home_dir()
                .ok_or_else(|| "Could not determine home directory".to_string())?;
            Ok(home.join(&p[2..]))
        } else {
            Ok(PathBuf::from(p))
        }
    };

    let monitors_path = expand_path(&settings.monitors_conf_path)?;
    let bak_path = expand_path(&settings.monitors_bak_path)?;
    let config_path = expand_path(&settings.config_conf_path)?;

    if !bak_path.exists() {
        if let Some(parent) = bak_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create backup directory: {}", e))?;
        }

        let collect_monitorrules = |path: &PathBuf| -> Vec<String> {
            let Ok(content) = fs::read_to_string(path) else {
                return Vec::new();
            };
            content
                .lines()
                .filter(|l| {
                    let t = l.trim();
                    t.starts_with("monitorrule=") || t.starts_with("monitorrule =")
                })
                .map(|l| l.to_string())
                .collect()
        };

        let resolve_source = |raw: &str| -> Result<PathBuf, String> {
            if raw.starts_with("~/") || raw.starts_with('/') {
                expand_path(raw)
            } else {
                let parent = config_path
                    .parent()
                    .ok_or_else(|| format!("Config path '{}' has no parent directory", config_path.display()))?;
                Ok(parent.join(raw))
            }
        };

        let to_portable = |p: &PathBuf| -> String {
            if let Some(home) = dirs::home_dir() {
                if let Ok(suffix) = p.strip_prefix(&home) {
                    return format!("~/{}", suffix.display());
                }
            }
            p.display().to_string()
        };

        let mut backup_entries: Vec<serde_json::Value> = Vec::new();

        if config_path.exists() {
            let direct_rules = collect_monitorrules(&config_path);
            if !direct_rules.is_empty() {
                backup_entries.push(serde_json::json!({
                    "source_file": to_portable(&config_path),
                    "rules": direct_rules,
                }));
            }

            if let Ok(content) = fs::read_to_string(&config_path) {
                for line in content.lines() {
                    let t = line.trim();
                    let sourced_path_str = if t.starts_with("source=") {
                        Some(t.trim_start_matches("source=").trim())
                    } else if t.starts_with("source =") {
                        Some(t.trim_start_matches("source =").trim())
                    } else {
                        None
                    };

                    if let Some(raw) = sourced_path_str {
                        if let Ok(sourced) = resolve_source(raw) {
                            let rules = collect_monitorrules(&sourced);
                            if !rules.is_empty() {
                                backup_entries.push(serde_json::json!({
                                    "source_file": to_portable(&sourced),
                                    "rules": rules,
                                }));
                            }
                        }
                    }
                }
            }
        }

        let backup_json = serde_json::json!({ "entries": backup_entries });
        let backup_json_str = serde_json::to_string_pretty(&backup_json)
            .map_err(|e| format!("Failed to serialize backup data: {}", e))?;
        fs::write(&bak_path, backup_json_str)
            .map_err(|e| format!("Failed to write monitors.bak: {}", e))?;
    }

    if let Some(parent) = monitors_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create monitors dir: {}", e))?;
    }

    fs::write(&monitors_path, script)
        .map_err(|e| format!("Failed to write monitors config: {}", e))?;

    if settings.auto_append_source {
        let source_line_tilde = format!("source={}", settings.monitors_conf_path);
        let source_line_abs = format!("source={}", monitors_path.display());
        let source_line_abs_spaced = format!("source = {}", monitors_path.display());
        let needs_source = if config_path.exists() {
            let content = fs::read_to_string(&config_path)
                .map_err(|e| format!("Failed to read config file: {}", e))?;
            !content.contains(&source_line_tilde)
                && !content.contains(&source_line_abs)
                && !content.contains(&source_line_abs_spaced)
        } else {
            true
        };

        if needs_source {
            use std::io::Write;
            if let Some(parent) = config_path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| format!("Failed to create config directory: {}", e))?;
            }
            let mut file = std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(&config_path)
                .map_err(|e| format!("Failed to open config file: {}", e))?;

            writeln!(file, "\n{}", source_line_tilde)
                .map_err(|e| format!("Failed to write config file source override: {}", e))?;
        }
    }

    Ok(())
}

pub fn restore_default_config(settings: &crate::settings::AppSettings) -> Result<(), String> {
    let expand_path = |p: &str| -> Result<PathBuf, String> {
        if p.starts_with("~/") {
            let home = dirs::home_dir()
                .ok_or_else(|| "Could not determine home directory".to_string())?;
            Ok(home.join(&p[2..]))
        } else {
            Ok(PathBuf::from(p))
        }
    };

    let config_path = expand_path(&settings.config_conf_path)?;
    let monitors_path = expand_path(&settings.monitors_conf_path)?;
    let bak_path = expand_path(&settings.monitors_bak_path)?;

    let backup: serde_json::Value = if bak_path.exists() {
        let raw = fs::read_to_string(&bak_path)
            .map_err(|e| format!("Failed to read monitors.bak: {}", e))?;
        serde_json::from_str(&raw).unwrap_or(serde_json::json!({ "entries": [] }))
    } else {
        serde_json::json!({ "entries": [] })
    };

    let entries = backup["entries"].as_array().cloned().unwrap_or_else(Vec::new);

    let strip_monitorrules = |content: &str| -> String {
        content
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.starts_with("monitorrule=") && !t.starts_with("monitorrule =")
            })
            .map(|l| format!("{}\n", l))
            .collect()
    };

    if config_path.exists() {
        let source_line_tilde = format!("source={}", settings.monitors_conf_path);
        let source_line_abs = format!("source={}", monitors_path.display());
        let source_line_abs_spaced = format!("source = {}", monitors_path.display());

        let content = fs::read_to_string(&config_path)
            .map_err(|e| format!("Failed to read config.conf: {}", e))?;

        let cleaned: String = content
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.starts_with("monitorrule=")
                    && !t.starts_with("monitorrule =")
                    && t != source_line_tilde.as_str()
                    && t != source_line_abs.as_str()
                    && t != source_line_abs_spaced.as_str()
            })
            .map(|l| format!("{}\n", l))
            .collect();

        fs::write(&config_path, cleaned)
            .map_err(|e| format!("Failed to write config.conf: {}", e))?;
    }

    for entry in &entries {
        if let (Some(source_file), Some(rules)) =
            (entry["source_file"].as_str(), entry["rules"].as_array())
        {
            let target_path = expand_path(source_file)?;
            let rules_block: String = rules
                .iter()
                .filter_map(|r| r.as_str())
                .map(|r| format!("{}\n", r))
                .collect();

            if rules_block.is_empty() {
                continue;
            }

            if target_path.exists() {
                let content = fs::read_to_string(&target_path)
                    .map_err(|e| format!("Failed to read {}: {}", target_path.display(), e))?;
                let cleaned = strip_monitorrules(&content);
                let restored = format!("{}\n{}", cleaned.trim_end(), rules_block);
                fs::write(&target_path, restored)
                    .map_err(|e| format!("Failed to restore rules to {}: {}", source_file, e))?;
            } else {
                if let Some(parent) = target_path.parent() {
                    fs::create_dir_all(parent)
                        .map_err(|e| format!("Failed to create directory for {}: {}", source_file, e))?;
                }
                fs::write(&target_path, rules_block)
                    .map_err(|e| format!("Failed to create {}: {}", source_file, e))?;
            }
        }
    }

    let monitors_was_backed_up = entries.iter().any(|e| {
        e["source_file"]
            .as_str()
            .map(|s| expand_path(s).map(|p| p == monitors_path).unwrap_or(false))
            .unwrap_or(false)
    });
    if monitors_path.exists() && !monitors_was_backed_up {
        fs::remove_file(&monitors_path)
            .map_err(|e| format!("Failed to delete monitors.conf: {}", e))?;
    }

    Ok(())
}
